# Generated by Django 4.0.5 on 2022-06-20 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigNewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_most_views', models.PositiveSmallIntegerField(verbose_name='Quantity most view')),
                ('number_category_news', models.PositiveSmallIntegerField(verbose_name='Quantity category news')),
                ('number_hot_news', models.PositiveSmallIntegerField(verbose_name='Quantity hot news')),
                ('number_editor_selection_news', models.PositiveSmallIntegerField(verbose_name='Quantity editor selection news')),
                ('status', models.CharField(blank=True, choices=[('p', 'Apply config'), (None, 'Draft config')], max_length=9, null=True, unique=True, verbose_name='Apply config')),
            ],
            options={
                'verbose_name': 'Config news',
                'verbose_name_plural': 'Config news',
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('title_fa', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='slug')),
                ('body', models.TextField(verbose_name='body')),
                ('body_en', models.TextField(null=True, verbose_name='body')),
                ('body_fa', models.TextField(null=True, verbose_name='body')),
                ('image', models.ImageField(upload_to='news/%Y/%m', verbose_name='image')),
                ('status', models.BooleanField(verbose_name='status published')),
                ('hotNews', models.BooleanField(default=False, verbose_name='hot news')),
                ('editor_selection', models.BooleanField(default=False, verbose_name='editor selection')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('category', models.ManyToManyField(related_name='news', to='base.categorymodel', verbose_name='category')),
                ('ip_address', models.ManyToManyField(blank=True, editable=False, related_name='visit', to='base.ipaddressmodel', verbose_name='ip address')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_writer', to='employee.employeesmodel', verbose_name='writer')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'news',
                'ordering': ['status', '-updated'],
            },
        ),
    ]
