# Generated by Django 4.0.5 on 2022-06-20 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('first_name_en', models.CharField(max_length=20, null=True, verbose_name='First Name')),
                ('first_name_fa', models.CharField(max_length=20, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('last_name_en', models.CharField(max_length=50, null=True, verbose_name='Last Name')),
                ('last_name_fa', models.CharField(max_length=50, null=True, verbose_name='Last Name')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('bio_en', models.TextField(null=True, verbose_name='Bio')),
                ('bio_fa', models.TextField(null=True, verbose_name='Bio')),
                ('profile_photo', models.ImageField(upload_to='employee/%Y/%m', verbose_name='Profile photo')),
                ('membership_date', models.DateField(verbose_name='Membership date')),
                ('rol', models.CharField(choices=[('w', 'writer'), ('p', 'photographer')], default='w', max_length=1, verbose_name='Rol')),
                ('counter', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'db_table': 'employee',
                'ordering': ['-last_name'],
            },
        ),
    ]
