# Generated by Django 4.0.5 on 2022-06-20 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('re_comment', models.TextField(blank=True, null=True, verbose_name='recommend')),
                ('full_name', models.CharField(max_length=80, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('status', models.BooleanField(default=False, verbose_name='status publish')),
                ('is_ready', models.BooleanField(default=False, verbose_name='is ready?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.newsmodel', verbose_name='news')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'comment',
                'ordering': ['-created'],
            },
        ),
    ]
